server:
  port: 8080 # ?? ?? ????

  # H2 Database ??
  # H2 DB 웹 콘솔 접근 주소 => http://localhost:8080/h2-console
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false

  datasource:
    url: 'jdbc:h2:mem:test'   # H2 DB ?? ?? (In-Memory Mode)
    #url: 'jdbc:h2:~/test'    # H2 DB ?? ?? (Embedded Mode)
    username: sa        # H2 DB ?? ID (??? ??)
    password:         # H2 DB ?? PW (??? ??)



  # H2 Console ??
  h2:
    console: # H2 DB? ??? ??? ? ?? ??
      enabled: true           # H2 Console ?? ??
      path: /h2-console       # H2 Console ?? ??

  # JPA ??
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update #JPA의 동작 방식        # DB ??? ?? (none, create, create-drop, update, validate)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true      # ?? ?? ?? (??)
        show_sql: true        # ?? ?? ??
